name: NaturalLink Regression Check
description:
  'Catch unintended UI regressions in AI-generated PRs before they ship'
author: naturallink.ai

branding:
  icon: monitor
  color: purple

inputs:
  api-key:
    required: true
    description: 'Your NaturalLink API key from dashboard.naturallink.ai'
  timeout:
    required: false
    description: 'Maximum wait time in seconds (default: 5 minutes)'
    default: '300'
  api-url:
    required: false
    description: 'API URL for enterprise deployments'
    default: 'https://api.naturallink.ai'
    deprecationMessage: 'For enterprise customers only'
  poll-interval:
    required: false
    description: 'Status check interval in seconds'
    default: '5'

outputs:
  status:
    description: 'Result of the check: SUCCESS or ERROR'
  error-message:
    description: 'Error details if the check failed'
  run-id:
    description: 'Internal run identifier for debugging'

runs:
  using: node20
  main: dist/index.js
