name: Bug Report
description: Report a bug or unexpected behavior
title: '[Bug]: '
labels: ['bug', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: When I run the action, it fails with...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Add workflow with configuration...
        2. Create a PR...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: workflow
    attributes:
      label: Workflow file
      description: Your workflow YAML (remove any secrets)
      render: yaml

  - type: textarea
    id: logs
    attributes:
      label: Action logs
      description: Relevant logs from the GitHub Actions run
      render: shell

  - type: dropdown
    id: runner
    attributes:
      label: Runner OS
      options:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        - self-hosted
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Action version
      description: Which version of the action are you using?
      placeholder: v0.3.0
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label:
            I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have removed any sensitive information from the logs/workflow
          required: true
